/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WritingID = IDL.Nat;
export const CategoryID = IDL.Nat;
export const Status = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Category = IDL.Record({
  'id' : CategoryID,
  'status' : Status,
  'title' : IDL.Text,
  'subcategoryIds' : IDL.Vec(CategoryID),
  'parentCategoryId' : IDL.Opt(CategoryID),
  'supportedLanguages' : IDL.Vec(IDL.Text),
  'focusBannerUrl' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const WritingState = IDL.Variant({
  'pending' : IDL.Null,
  'published' : IDL.Null,
  'rejected' : IDL.Null,
  'draft' : IDL.Null,
});
export const Writing = IDL.Record({
  'id' : WritingID,
  'categories' : IDL.Vec(CategoryID),
  'title' : IDL.Text,
  'content' : IDL.Text,
  'contentWarnings' : IDL.Vec(IDL.Text),
  'submissions' : IDL.Nat,
  'author' : IDL.Opt(IDL.Principal),
  'state' : WritingState,
  'parentPageId' : IDL.Opt(WritingID),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'associateCategory' : IDL.Func([WritingID, CategoryID], [], []),
  'categoryHasLanguages' : IDL.Func(
      [CategoryID, IDL.Vec(IDL.Text)],
      [IDL.Bool],
      ['query'],
    ),
  'createCategory' : IDL.Func(
      [IDL.Text, IDL.Opt(CategoryID), IDL.Vec(IDL.Text), IDL.Text, Status],
      [CategoryID],
      [],
    ),
  'deleteCategory' : IDL.Func([CategoryID], [], []),
  'deleteWriting' : IDL.Func([WritingID], [], []),
  'getActiveChildCategories' : IDL.Func(
      [IDL.Opt(CategoryID)],
      [IDL.Vec(Category)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func(
      [IDL.Opt(CategoryID)],
      [IDL.Vec(Category)],
      ['query'],
    ),
  'getCategory' : IDL.Func([CategoryID], [Category], ['query']),
  'getPublishedWritings' : IDL.Func([], [IDL.Vec(Writing)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWriting' : IDL.Func([WritingID], [Writing], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'migrateWritings' : IDL.Func([], [IDL.Nat], []),
  'publishWriting' : IDL.Func([WritingID], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitWriting' : IDL.Func(
      [IDL.Text, IDL.Vec(CategoryID), IDL.Text, IDL.Vec(IDL.Text)],
      [WritingID],
      [],
    ),
  'unpublishWriting' : IDL.Func([WritingID], [], []),
  'updateCategory' : IDL.Func(
      [
        CategoryID,
        IDL.Text,
        IDL.Opt(CategoryID),
        IDL.Vec(IDL.Text),
        IDL.Text,
        Status,
      ],
      [],
      [],
    ),
  'updateWriting' : IDL.Func(
      [WritingID, IDL.Text, IDL.Text, IDL.Vec(CategoryID), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WritingID = IDL.Nat;
  const CategoryID = IDL.Nat;
  const Status = IDL.Variant({ 'active' : IDL.Null, 'inactive' : IDL.Null });
  const Category = IDL.Record({
    'id' : CategoryID,
    'status' : Status,
    'title' : IDL.Text,
    'subcategoryIds' : IDL.Vec(CategoryID),
    'parentCategoryId' : IDL.Opt(CategoryID),
    'supportedLanguages' : IDL.Vec(IDL.Text),
    'focusBannerUrl' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const WritingState = IDL.Variant({
    'pending' : IDL.Null,
    'published' : IDL.Null,
    'rejected' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Writing = IDL.Record({
    'id' : WritingID,
    'categories' : IDL.Vec(CategoryID),
    'title' : IDL.Text,
    'content' : IDL.Text,
    'contentWarnings' : IDL.Vec(IDL.Text),
    'submissions' : IDL.Nat,
    'author' : IDL.Opt(IDL.Principal),
    'state' : WritingState,
    'parentPageId' : IDL.Opt(WritingID),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'associateCategory' : IDL.Func([WritingID, CategoryID], [], []),
    'categoryHasLanguages' : IDL.Func(
        [CategoryID, IDL.Vec(IDL.Text)],
        [IDL.Bool],
        ['query'],
      ),
    'createCategory' : IDL.Func(
        [IDL.Text, IDL.Opt(CategoryID), IDL.Vec(IDL.Text), IDL.Text, Status],
        [CategoryID],
        [],
      ),
    'deleteCategory' : IDL.Func([CategoryID], [], []),
    'deleteWriting' : IDL.Func([WritingID], [], []),
    'getActiveChildCategories' : IDL.Func(
        [IDL.Opt(CategoryID)],
        [IDL.Vec(Category)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func(
        [IDL.Opt(CategoryID)],
        [IDL.Vec(Category)],
        ['query'],
      ),
    'getCategory' : IDL.Func([CategoryID], [Category], ['query']),
    'getPublishedWritings' : IDL.Func([], [IDL.Vec(Writing)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWriting' : IDL.Func([WritingID], [Writing], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'migrateWritings' : IDL.Func([], [IDL.Nat], []),
    'publishWriting' : IDL.Func([WritingID], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitWriting' : IDL.Func(
        [IDL.Text, IDL.Vec(CategoryID), IDL.Text, IDL.Vec(IDL.Text)],
        [WritingID],
        [],
      ),
    'unpublishWriting' : IDL.Func([WritingID], [], []),
    'updateCategory' : IDL.Func(
        [
          CategoryID,
          IDL.Text,
          IDL.Opt(CategoryID),
          IDL.Vec(IDL.Text),
          IDL.Text,
          Status,
        ],
        [],
        [],
      ),
    'updateWriting' : IDL.Func(
        [WritingID, IDL.Text, IDL.Text, IDL.Vec(CategoryID), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };