/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : CategoryID,
  'status' : Status,
  'title' : string,
  'subcategoryIds' : Array<CategoryID>,
  'parentCategoryId' : [] | [CategoryID],
  'supportedLanguages' : Array<string>,
  'focusBannerUrl' : string,
}
export type CategoryID = bigint;
export type Status = { 'active' : null } |
  { 'inactive' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Writing {
  'id' : WritingID,
  'categories' : Array<CategoryID>,
  'title' : string,
  'content' : string,
  'contentWarnings' : Array<string>,
  'submissions' : bigint,
  'author' : [] | [Principal],
  'state' : WritingState,
  'parentPageId' : [] | [WritingID],
}
export type WritingID = bigint;
export type WritingState = { 'pending' : null } |
  { 'published' : null } |
  { 'rejected' : null } |
  { 'draft' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'associateCategory' : ActorMethod<[WritingID, CategoryID], undefined>,
  'categoryHasLanguages' : ActorMethod<[CategoryID, Array<string>], boolean>,
  'createCategory' : ActorMethod<
    [string, [] | [CategoryID], Array<string>, string, Status],
    CategoryID
  >,
  'deleteCategory' : ActorMethod<[CategoryID], undefined>,
  'deleteWriting' : ActorMethod<[WritingID], undefined>,
  'getActiveChildCategories' : ActorMethod<
    [[] | [CategoryID]],
    Array<Category>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[[] | [CategoryID]], Array<Category>>,
  'getCategory' : ActorMethod<[CategoryID], Category>,
  'getPublishedWritings' : ActorMethod<[], Array<Writing>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWriting' : ActorMethod<[WritingID], Writing>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'migrateWritings' : ActorMethod<[], bigint>,
  'publishWriting' : ActorMethod<[WritingID], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitWriting' : ActorMethod<
    [string, Array<CategoryID>, string, Array<string>],
    WritingID
  >,
  'unpublishWriting' : ActorMethod<[WritingID], undefined>,
  'updateCategory' : ActorMethod<
    [CategoryID, string, [] | [CategoryID], Array<string>, string, Status],
    undefined
  >,
  'updateWriting' : ActorMethod<
    [WritingID, string, string, Array<CategoryID>, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];